### ISSUE TITLE
还会更新吗

### ISSUE THREAD

**Issue by FredKele** [MengLuwa/ArkNightsForMinor#13]
大佬还会继续更新吗 Tao0Lu大佬的我用不好 作为纯小白总是出错

**Comment by MengLuwa** [comment]
应该会吧，最近在肝原神，等时间空下来了

**Comment by FredKele** [comment]
好的 十分感谢大佬

**Comment by long45343** [comment]
> 大佬还会继续更新吗 Tao0Lu大佬的我用不好 作为纯小白总是出错



> 好的 十分感谢大佬

要不我自己搞个教程？
2333333

**Comment by FredKele** [comment]
当然可以啊 如果学不会的话就只能靠大佬的更新了（小白的凝视）
