### ISSUE TITLE
雷电实测不行

### ISSUE THREAD

**Issue by long45343** [MengLuwa/ArkNightsForMinor#2]
有时间继续测试

**Comment by MengLuwa** [comment]
> 有时间继续测试

需要支持ARM环境的模拟器，而且安装的时候要以arm安装。所以最好真机上

**Comment by long45343** [comment]
> > 有时间继续测试
> 
> 需要支持ARM环境的模拟器，而且安装的时候要以arm安装。所以最好真机上

ok现在手机测试

**Comment by long45343** [comment]
真机测试也不行....

**Comment by MengLuwa** [comment]
> 真机测试也不行....

不行的话就写出是什么情况，就说个不行谁知道什么问题

**Comment by long45343** [comment]
> > 真机测试也不行....
> 
> 不行的话就写出是什么情况，就说个不行谁知道什么问题

就是像没有破解过一样...

**Comment by MengLuwa** [comment]
> > > 真机测试也不行....
> > 
> > 
> > 不行的话就写出是什么情况，就说个不行谁知道什么问题
> 
> 就是像没有破解过一样...

首先确定你的手机是否是ARM系统，然后是否存在大更新，如果存在大更新，就可能是更新覆盖了修改

**Comment by long45343** [comment]
> > > > 真机测试也不行....
> > > 
> > > 
> > > 不行的话就写出是什么情况，就说个不行谁知道什么问题
> > 
> > 
> > 就是像没有破解过一样...
> 
> 首先确定你的手机是否是ARM系统，然后是否存在大更新，如果存在大更新，就可能是更新覆盖了修改

版本没有更新过，就是闪断更新，支持armv7a指令集（骁龙625安卓Q）
话说修改过的文件在apk中的目录是什么

**Comment by MengLuwa** [comment]
> > > > > 真机测试也不行....
> > > > 
> > > > 
> > > > 不行的话就写出是什么情况，就说个不行谁知道什么问题
> > > 
> > > 
> > > 就是像没有破解过一样...
> > 
> > 
> > 首先确定你的手机是否是ARM系统，然后是否存在大更新，如果存在大更新，就可能是更新覆盖了修改
> 
> 版本没有更新过，就是闪断更新，支持armv7a指令集（骁龙625安卓Q）
> 话说修改过的文件在apk中的目录是什么

修改过的文件是libSougou.so，芯片没有问题，但是闪断更新不确定，因为搭在了XLUA热更新，可能存在热更新改变代码逻辑的情况，如果是这样我就只能找时间看看了。你看看你的安装的lib目录下有没有libSougou.so，有而且可以正常运行的情况的话，那么就可能是热更新问题或者服务器那边换了验证方法

**Comment by long45343** [comment]
\data\app\包名\lib下面有

**Comment by MengLuwa** [comment]
> \data\app\包名\lib下面有

那就只能抽时间再看了，你是打开之后未成年验证照旧吧

**Comment by long45343** [comment]
> > \data\app\包名\lib下面有
> 
> 那就只能抽时间再看了，你是打开之后未成年验证照旧吧

是的，未成年账号【doge】

**Comment by long45343** [comment]
对了，危机合约版本的pj会有吗😂

**Comment by long45343** [comment]
【doge】
