### ISSUE TITLE
新版本还会更新吗？

### ISSUE THREAD

**Issue by WeiEAL** [MengLuwa/ArkNightsForMinor#4]
百度找到了nga帖子快照，可是版本已经更新用不了了，大佬还会更新版本吗

**Comment by MengLuwa** [comment]
> 百度找到了nga帖子快照，可是版本已经更新用不了了，大佬还会更新版本吗

大概近几天就找个时间更新吧……

**Comment by WeiEAL** [comment]
> > 百度找到了nga帖子快照，可是版本已经更新用不了了，大佬即将更新版本吗
> 
> 大概近几天就找个时间更新吧……

不知道说什么好，，辛苦了

**Comment by long45343** [comment]
辛苦了
