### ISSUE TITLE
新版到时间进不去游戏

### ISSUE THREAD

**Issue by WeiEAL** [MengLuwa/ArkNightsForMinor#5]
本来以为可以一直挂着了，但是刚刚发现游戏闪退，再上游戏就提示时间到了
![QQ截图20200607165251](https://user-images.githubusercontent.com/47446553/83964418-9fc6ca00-a8df-11ea-87d4-1f0316f6bf1d.png)

是鹰角修复了这个bug吗,,

**Comment by MengLuwa** [comment]
> 本来以为可以一直挂着了，但是刚刚发现游戏闪退，再上游戏就提示时间到了
> ![QQ截图20200607165251](https://user-images.githubusercontent.com/47446553/83964418-9fc6ca00-a8df-11ea-87d4-1f0316f6bf1d.png)
> 
> 是鹰角修复了这个bug吗,,

首先确定你是否是armeabi-v7a模式安装的，如果是的话，那可能有其它问题，我用无验证账号测试没出现错误。至于未成年账号，我没有，只能靠猜测来搞，如果你愿意的话，可以加我的qq借我账号帮我测试

**Comment by WeiEAL** [comment]
> > 本来以为可以一直挂着了，但是刚刚发现游戏闪退，再上游戏就提示时间到了
> > ![QQ截图20200607165251](https://user-images.githubusercontent.com/47446553/83964418-9fc6ca00-a8df-11ea-87d4-1f0316f6bf1d.png)
> > 是鹰角修复了这个bug吗,,
> 
> 首先确定你是否是armeabi-v7a模式安装的，如果是的话，那可能有其它问题，我用无验证账号测试没出现错误。至于未成年账号，我没有，只能靠猜测来搞，如果你愿意的话，可以加我的qq借我账号帮我测试

大佬QQ多少，我加一下
