### ISSUE TITLE
充值限制没有解除，时间限制测试中

### ISSUE THREAD

**Issue by long45343** [MengLuwa/ArkNightsForMinor#7]
..

**Comment by long45343** [comment]
好了正常 😀

**Comment by MengLuwa** [comment]
因为怂和懒两个原因，我删掉了充值验证解除的功能，免得上新闻

**Comment by long45343** [comment]
https://honoka-my.sharepoint.com/:u:/g/personal/msm8940_lily_beer/ETl8wdUTH-pLp2B6Z5zS31kBysfLOMvs9qI3boF_TananA?e=XigJwU
包名我自己改回去了（为了jio本2333）
这个是Onedrive链接
